### ISSUE TITLE
Error running Gradle

### ISSUE THREAD

**Issue by alikopasa** [efortuna/memechat#26]
Hello,
I cloned memechat and did everything as you mentioned in Usage. (with skipping IOS)
But i'm gettin below error. Can you help me please?

Regards,
Ali

* Error running Gradle:
Exit code 1 from: /Users/alikopasa/Documents/FlutterProjects/memechat/android/gradlew app:properties:
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/alikopasa/Documents/FlutterProjects/memechat/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not resolve all dependencies for configuration ':app:_debugApk'.
      > A problem occurred configuring project ':firebase_auth'.
         > Failed to notify project evaluation listener.
            > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUİLD FAILED in 1s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by kgcorner** [comment]
I am also facing this issue. do anyone have solution?

**Comment by Soundbytes** [comment]
You need to update the files
android.manifest
android/build.gradle
app/build.gradle

To reenable the android build I created a fresh flutter project and then replaced all of the boiler plate in the memechat that seemed outdated to me with the newer code. 
You'll find my fork of the project here: https://github.com/Soundbytes/memechat

Disclaimer: As I am fairly new to flutter I have no Idea if all the changes I made are really neccessary to get the build going again nor do I know wether I have inadvertently damaged anything.

**Comment by efortuna** [comment]
I believe this is fixed now thanks to @Soundbytes contribution! Thank you!

**Comment by chonghorizons** [comment]
This appears not to be fixed, as I'm getting a bunch of build errors still. I changed some of the things according to https://github.com/Soundbytes/memechat (thanks @Soundbytes ) but I still get errors. Most notably database not connecting errors.

Working on it now. #41 is the issue I filed.
